# Generated by Django 5.2.17 on 2026-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cut', 'Haircuts'), ('braid', 'Braiding'), ('colour', 'Colouring'), ('style', 'Styling'), ('beard', 'Beard Grooming')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hairstyles/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
