# Generated by Django 5.2.17 on 2026-09-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('senior', 'Senior Stylist'), ('colour', 'Colour Specialist'), ('junior', 'Junior Stylist'), ('barber', 'Barber / Beard Specialist')], default='senior', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stylists/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='stylists.stylist')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('stylist', 'day_of_week')},
            },
        ),
    ]
